In [24]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 

os.chdir("C:/Users/FARIYA/Desktop")
df = pd.read_csv('heart 2.csv',header=0)
display(df)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [25]:
df.drop(df.index[0],inplace=True)
df.drop(df.index[1],inplace=True)
df.drop(df.index[2],inplace=True)
df.drop(df.index[3],inplace=True)
df.drop(df.index[4],inplace=True)
df.drop(df.index[5],inplace=True)
df.drop(df.index[6],inplace=True)
df.drop(df.index[7],inplace=True)
df.drop(df.index[8],inplace=True)

In [26]:
df1 = pd.read_csv('heart 3.csv')
display(df1)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [27]:
df1.drop(df1.index[0],inplace=True)
df1.drop(df1.index[1],inplace=True)
df1.drop(df1.index[2],inplace=True)
df1.drop(df1.index[3],inplace=True)
df1.drop(df1.index[4],inplace=True)

In [28]:
df['platelets']=df1['platelets']
df['smoking']=df1['smoking']
df['high_blood_pressure']=df1['high_blood_pressure']
df['anaemia']=df1['anaemia']

In [29]:
df=df[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','platelets','high_blood_pressure','anaemia','smoking','target']]
df=df.copy()

In [30]:
display(df)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1     37    1   2       130   250    0        1      187      0      3.5   
3     56    1   1       120   236    0        1      178      0      0.8   
5     57    1   0       140   192    0        1      148      0      0.4   
7     44    1   1       120   263    0        1      173      0      0.0   
9     57    1   2       150   168    0        1      174      0      1.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  platelets  high_blood_pressure  anaemia  smoking  target  
1        0   0     2  263358.03                  0.0      0.0      0.0       1  
3        2   0     2  210000.00                  0.0      1.0      0.0       1  
5        1   0     1  204000.00                  1.0      1.0      1.0       1  
7        2   0     3  454000.00                  0.0      1.0      1.0       1  
9        2   0     2  388000.00                  1.0      1.0      1.0       1  
..     ...  ..   ...        ...                  ...      ...      ...     ...  
298      1   0     3  395000.00                  0.0      0.0      1.0       0  
299      1   0     3        NaN                  NaN      NaN      NaN       0  
300      1   2     3        NaN                  NaN      NaN      NaN       0  
301      1   1     3        NaN                  NaN      NaN      NaN       0  
302      1   1     2        NaN                  NaN      NaN      NaN       0  

[294 rows x 18 columns]

In [31]:
df.shape

(294, 18)

In [32]:
df.dtypes

age                      int64
sex                      int64
cp                       int64
trestbps                 int64
chol                     int64
fbs                      int64
restecg                  int64
thalach                  int64
exang                    int64
oldpeak                float64
slope                    int64
ca                       int64
thal                     int64
platelets              float64
high_blood_pressure    float64
anaemia                float64
smoking                float64
target                   int64
dtype: object

In [33]:
df.isnull().sum()

age                    0
sex                    0
cp                     0
trestbps               0
chol                   0
fbs                    0
restecg                0
thalach                0
exang                  0
oldpeak                0
slope                  0
ca                     0
thal                   0
platelets              4
high_blood_pressure    4
anaemia                4
smoking                4
target                 0
dtype: int64

In [34]:
median=df['platelets'].median()
df['platelets'].fillna(median, inplace=True)

In [35]:
median=df['high_blood_pressure'].median()
df['high_blood_pressure'].fillna(median, inplace=True)

In [36]:
median=df['anaemia'].median()
df['anaemia'].fillna(median, inplace=True)

In [37]:
median=df['smoking'].median()
df['smoking'].fillna(median, inplace=True)

In [38]:
df['platelets'] = df['platelets'].astype(int)
df['high_blood_pressure'] = df['high_blood_pressure'].astype(int)
df['anaemia'] = df['anaemia'].astype(int)
df['smoking'] = df['smoking'].astype(int)

In [39]:
df.dtypes

age                      int64
sex                      int64
cp                       int64
trestbps                 int64
chol                     int64
fbs                      int64
restecg                  int64
thalach                  int64
exang                    int64
oldpeak                float64
slope                    int64
ca                       int64
thal                     int64
platelets                int32
high_blood_pressure      int32
anaemia                  int32
smoking                  int32
target                   int64
dtype: object

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 294 entries, 1 to 302
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  294 non-null    int64  
 1   sex                  294 non-null    int64  
 2   cp                   294 non-null    int64  
 3   trestbps             294 non-null    int64  
 4   chol                 294 non-null    int64  
 5   fbs                  294 non-null    int64  
 6   restecg              294 non-null    int64  
 7   thalach              294 non-null    int64  
 8   exang                294 non-null    int64  
 9   oldpeak              294 non-null    float64
 10  slope                294 non-null    int64  
 11  ca                   294 non-null    int64  
 12  thal                 294 non-null    int64  
 13  platelets            294 non-null    int32  
 14  high_blood_pressure  294 non-null    int32  
 15  anaemia              294 non-null    int

In [41]:
corr_mat=df.corr()
corr_mat

age       sex        cp  trestbps      chol  \
age                  1.000000 -0.102389 -0.078979  0.284007  0.209672   
sex                 -0.102389  1.000000 -0.045428 -0.066136 -0.179767   
cp                  -0.078979 -0.045428  1.000000  0.030604 -0.079998   
trestbps             0.284007 -0.066136  0.030604  1.000000  0.139742   
chol                 0.209672 -0.179767 -0.079998  0.139742  1.000000   
fbs                  0.115251  0.042052  0.056857  0.150689  0.023713   
restecg             -0.117755 -0.070298  0.059161 -0.113969 -0.163856   
thalach             -0.399359 -0.033410  0.297580 -0.050911 -0.018879   
exang                0.095996  0.145671 -0.389230  0.082609  0.062983   
oldpeak              0.210740  0.093855 -0.156019  0.194318  0.063643   
slope               -0.161513 -0.016896  0.132678 -0.126684 -0.014749   
ca                   0.279986  0.110222 -0.175671  0.112488  0.081792   
thal                 0.075770  0.209064 -0.154161  0.061751  0.112387   
platelets           -0.005314  0.007814 -0.045752 -0.049259 -0.025974   
high_blood_pressure -0.045959  0.055204  0.075635 -0.052585 -0.056936   
anaemia             -0.044186 -0.028765 -0.007682 -0.105285  0.016488   
smoking             -0.065278  0.001502 -0.017945  0.087098 -0.067188   
target              -0.229426 -0.275899  0.434736 -0.160289 -0.100056   

                          fbs   restecg   thalach     exang   oldpeak  \
age                  0.115251 -0.117755 -0.399359  0.095996  0.210740   
sex                  0.042052 -0.070298 -0.033410  0.145671  0.093855   
cp                   0.056857  0.059161  0.297580 -0.389230 -0.156019   
trestbps             0.150689 -0.113969 -0.050911  0.082609  0.194318   
chol                 0.023713 -0.163856 -0.018879  0.062983  0.063643   
fbs                  1.000000 -0.076586 -0.012344  0.041239 -0.000237   
restecg             -0.076586  1.000000  0.040126 -0.077761 -0.048474   
thalach             -0.012344  0.040126  1.000000 -0.377040 -0.343645   
exang                0.041239 -0.077761 -0.377040  1.000000  0.294176   
oldpeak             -0.000237 -0.048474 -0.343645  0.294176  1.000000   
slope               -0.054479  0.077944  0.381175 -0.263425 -0.577735   
ca                   0.155295 -0.072430 -0.203561  0.107591  0.224465   
thal                -0.024937 -0.022020 -0.092053  0.204184  0.221774   
platelets           -0.101524 -0.009504 -0.017157  0.023386 -0.045172   
high_blood_pressure -0.032090 -0.051310 -0.040898 -0.045475 -0.009746   
anaemia             -0.030965 -0.063561  0.056178 -0.087762 -0.110423   
smoking              0.032752 -0.104832  0.100252 -0.082514 -0.030931   
target              -0.044519  0.139408  0.413717 -0.433736 -0.436999   

                        slope        ca      thal  platelets  \
age                 -0.161513  0.279986  0.075770  -0.005314   
sex                 -0.016896  0.110222  0.209064   0.007814   
cp                   0.132678 -0.175671 -0.154161  -0.045752   
trestbps            -0.126684  0.112488  0.061751  -0.049259   
chol                -0.014749  0.081792  0.112387  -0.025974   
fbs                 -0.054479  0.155295 -0.024937  -0.101524   
restecg              0.077944 -0.072430 -0.022020  -0.009504   
thalach              0.381175 -0.203561 -0.092053  -0.017157   
exang               -0.263425  0.107591  0.204184   0.023386   
oldpeak             -0.577735  0.224465  0.221774  -0.045172   
slope                1.000000 -0.072704 -0.119462   0.021222   
ca                  -0.072704  1.000000  0.143584  -0.106942   
thal                -0.119462  0.143584  1.000000   0.106282   
platelets            0.021222 -0.106942  0.106282   1.000000   
high_blood_pressure  0.059599 -0.185358  0.023809   0.030823   
anaemia              0.111453 -0.009785 -0.019643  -0.050477   
smoking             -0.021087 -0.096883 -0.135432   0.028139   
target               0.345158 -0.379552 -0.338352   0.024092   

                     high_blood_p

In [42]:
print(corr_mat['target'].sort_values(ascending=False))

target                 1.000000
cp                     0.434736
thalach                0.413717
slope                  0.345158
high_blood_pressure    0.170068
restecg                0.139408
anaemia                0.120682
smoking                0.031017
platelets              0.024092
fbs                   -0.044519
chol                  -0.100056
trestbps              -0.160289
age                   -0.229426
sex                   -0.275899
thal                  -0.338352
ca                    -0.379552
exang                 -0.433736
oldpeak               -0.436999
Name: target, dtype: float64


In [43]:
#Here, we can see that cp,thalach,slope,high_blood pressure, restecg,anaemia,smoking,platelets has impact on the target variable therefore, will keep only these features.

In [44]:
df.drop(['fbs'],axis=1,inplace=True)
df.drop(['chol'],axis=1,inplace=True)
df.drop(['trestbps'],axis=1,inplace=True)
df.drop(['age'],axis=1,inplace=True)
df.drop(['sex'],axis=1,inplace=True)
df.drop(['thal'],axis=1,inplace=True)
df.drop(['ca'],axis=1,inplace=True)
df.drop(['exang'],axis=1,inplace=True)
df.drop(['oldpeak'],axis=1,inplace=True)

In [45]:
df.head()

cp  restecg  thalach  slope  platelets  high_blood_pressure  anaemia  \
1   2        1      187      0     263358                    0        0   
3   1        1      178      2     210000                    0        1   
5   0        1      148      1     204000                    1        1   
7   1        1      173      2     454000                    0        1   
9   2        1      174      2     388000                    1        1   

   smoking  target  
1        0       1  
3        0       1  
5        1       1  
7        1       1  
9        1       1

In [46]:
y=df['target']

In [47]:
df.drop(['target'],axis=1,inplace=True)

In [48]:
x=df

In [49]:
# Scaling all the variables to a range of 0 to 1
from sklearn.preprocessing import MinMaxScaler
features = x.columns.values
scaler = MinMaxScaler(feature_range = (0,1))
scaler.fit(x)
x = pd.DataFrame(scaler.transform(x))
x.columns = features

In [50]:
xtrain , xtest , ytrain, ytest =train_test_split(x,y,test_size=0.2,random_state=101)

In [51]:
print("xtrain shape : ", xtrain.shape) 
print("xtest shape  : ", xtest.shape) 
print("ytrain shape : ", ytrain.shape) 
print("ytest shape  : ", ytest.shape) 

xtrain shape :  (235, 8)
xtest shape  :  (59, 8)
ytrain shape :  (235,)
ytest shape  :  (59,)


# KNN

In [52]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=9)
result=model.fit(xtrain, ytrain);

In [172]:
# K= 5
# 0.7457
# K=9
# 0.7966
# K= 11
# 0.7796
# K= 15
# 0.7966

In [53]:
from sklearn import metrics
prediction_test = model.predict(xtest)
accuracy = metrics.accuracy_score(ytest, prediction_test)
print(accuracy)

0.7966101694915254


In [54]:
prediction_test = model.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
print()
print ("MODEL ACCURACY:" "\n", accuracy)
print()
print("CONFUSION MATRIX:" "\n", confusion_matrix)
print()
print("CLASSIFICATION REPORT:" "\n", classification) 
print()



MODEL ACCURACY:
 0.7966101694915254

CONFUSION MATRIX:
 [[23 11]
 [ 1 24]]

CLASSIFICATION REPORT:
               precision    recall  f1-score   support

           0       0.96      0.68      0.79        34
           1       0.69      0.96      0.80        25

    accuracy                           0.80        59
   macro avg       0.82      0.82      0.80        59
weighted avg       0.84      0.80      0.80        59




# Naive Bayes

In [55]:
#Create a Bernoulli Classifier
from sklearn.naive_bayes import BernoulliNB 
modelB = BernoulliNB()
modelB.fit(xtrain, ytrain); 

In [56]:
from sklearn import metrics

prediction_test = modelB.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.8813559322033898

Confusion matrix:
 [[30  4]
 [ 3 22]]

Classification report:
               precision    recall  f1-score   support

           0       0.91      0.88      0.90        34
           1       0.85      0.88      0.86        25

    accuracy                           0.88        59
   macro avg       0.88      0.88      0.88        59
weighted avg       0.88      0.88      0.88        59




In [57]:
#Create a Gaussian Classifier
from sklearn.naive_bayes import GaussianNB
modelnB = GaussianNB()
modelnB.fit(xtrain, ytrain); 

In [58]:
from sklearn import metrics

prediction_test = modelnB.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.8305084745762712

Confusion matrix:
 [[26  8]
 [ 2 23]]

Classification report:
               precision    recall  f1-score   support

           0       0.93      0.76      0.84        34
           1       0.74      0.92      0.82        25

    accuracy                           0.83        59
   macro avg       0.84      0.84      0.83        59
weighted avg       0.85      0.83      0.83        59




In [59]:
#Create a Multinomial Classifier
from sklearn.naive_bayes import MultinomialNB
modelMB = MultinomialNB()
modelMB.fit(xtrain, ytrain); 

In [60]:
from sklearn import metrics

prediction_test = modelMB.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.5084745762711864

Confusion matrix:
 [[ 8 26]
 [ 3 22]]

Classification report:
               precision    recall  f1-score   support

           0       0.73      0.24      0.36        34
           1       0.46      0.88      0.60        25

    accuracy                           0.51        59
   macro avg       0.59      0.56      0.48        59
weighted avg       0.61      0.51      0.46        59




# Decisin Tree

In [63]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',max_depth=3)
result = classifier.fit(xtrain, ytrain);
classifier.score(xtrain, ytrain)

0.7574468085106383

In [64]:
from sklearn import metrics
prediction_test = classifier.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.8813559322033898

Confusion matrix:
 [[30  4]
 [ 3 22]]

Classification report:
               precision    recall  f1-score   support

           0       0.91      0.88      0.90        34
           1       0.85      0.88      0.86        25

    accuracy                           0.88        59
   macro avg       0.88      0.88      0.88        59
weighted avg       0.88      0.88      0.88        59




In [183]:
classifier_entropy = DecisionTreeClassifier(criterion='entropy')
result = classifier_entropy.fit(xtrain, ytrain);

In [184]:
from sklearn import metrics
prediction_test = classifier_entropy.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.711864406779661

Confusion matrix:
 [[23 11]
 [ 6 19]]

Classification report:
               precision    recall  f1-score   support

           0       0.79      0.68      0.73        34
           1       0.63      0.76      0.69        25

    accuracy                           0.71        59
   macro avg       0.71      0.72      0.71        59
weighted avg       0.73      0.71      0.71        59




# SVM Algorithm

In [185]:
from sklearn.svm import SVC
model = SVC(kernel='linear')
result = model.fit(xtrain, ytrain);

In [186]:
from sklearn import metrics

prediction_test = model.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.9152542372881356

Confusion matrix:
 [[30  4]
 [ 1 24]]

Classification report:
               precision    recall  f1-score   support

           0       0.97      0.88      0.92        34
           1       0.86      0.96      0.91        25

    accuracy                           0.92        59
   macro avg       0.91      0.92      0.91        59
weighted avg       0.92      0.92      0.92        59




# Random Forest

In [187]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,auc
clf = RandomForestClassifier(n_estimators=100,criterion='gini')
clf.fit(xtrain, ytrain)
predictions = clf.predict(xtest)
print("Accuracy of RandomForest (%): \n", accuracy_score(ytest, predictions)*100)

Accuracy of RandomForest (%): 
 77.96610169491525


In [188]:
from sklearn import metrics

prediction_test = clf.predict(X_test)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.7796610169491526

Confusion matrix:
 [[26  8]
 [ 5 20]]

Classification report:
               precision    recall  f1-score   support

           0       0.84      0.76      0.80        34
           1       0.71      0.80      0.75        25

    accuracy                           0.78        59
   macro avg       0.78      0.78      0.78        59
weighted avg       0.79      0.78      0.78        59




# AdaBoost Classifier

In [55]:
from sklearn.ensemble import  AdaBoostClassifier
model = AdaBoostClassifier()
result = model.fit(xtrain, ytrain);

In [56]:
from sklearn import metrics

prediction_test = model.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.7966101694915254

Confusion matrix:
 [[26  8]
 [ 4 21]]

Classification report:
               precision    recall  f1-score   support

           0       0.87      0.76      0.81        34
           1       0.72      0.84      0.78        25

    accuracy                           0.80        59
   macro avg       0.80      0.80      0.80        59
weighted avg       0.81      0.80      0.80        59




# Gradient Boosting

In [57]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
result = model.fit(xtrain, ytrain);

In [58]:
from sklearn import metrics

prediction_test = model.predict(xtest)
# Print the prediction accuracy
accuracy = metrics.accuracy_score(ytest, prediction_test)
confusion_matrix = metrics.confusion_matrix(ytest, prediction_test)
classification = metrics.classification_report(ytest, prediction_test)
print()
#print('============================== Model Evaluation =============================='.format(i))
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()



Model Accuracy:
 0.8983050847457628

Confusion matrix:
 [[30  4]
 [ 2 23]]

Classification report:
               precision    recall  f1-score   support

           0       0.94      0.88      0.91        34
           1       0.85      0.92      0.88        25

    accuracy                           0.90        59
   macro avg       0.89      0.90      0.90        59
weighted avg       0.90      0.90      0.90        59


